# Site settings
title: Selectize.JS
email: selectize@risadams.com
description: Documentation and demos for the selectize.js library
baseurl: "" # The subpath of your site, e.g. /blog
url: "https://selectize.dev" # The base hostname & protocol for your site

markdown: kramdown
permalink: pretty
highlighter: rouge

plugins:
  - jekyll/tagging

include:
  - _pages

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - README.md
  - SECURITY.md
  - SUPPORT.md
  - LICENSE

sass:
  style: compressed

# Tags
tag_page_dir: tag
tag_page_layout: tag_page
tag_permalink_style: pretty

# Pages path
defaults:
  - scope:
      path: "_pages"
    values:
      permalink: /:basename:output_ext
